### ISSUE TITLE
json not found error

### ISSUE THREAD

**Issue by cupOJoseph** [NimaBoscarino/PlaceYourself#1]
```
Error: ENOENT: no such file or directory, open 'public/defs/ship.json'
    at Object.openSync (fs.js:438:3)
    at Object.readFileSync (fs.js:343:35)
    at selectImage (/app/server.js:16:28)
    at /app/server.js:87:20
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22
    at param (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:354:14)
```

When creating a collection:
```
{ width: 912, height: 545, type: 'png' }
{ width: 687, height: 489, type: 'png' }
{ width: 669, height: 497, type: 'png' }
{ width: 671, height: 526, type: 'png' }
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'public/defs/ship.json'
    at Object.openSync (fs.js:438:3)
    at Object.writeFileSync (fs.js:1189:35)
    at /app/server.js:149:14
    at xfs.stat (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/fs-extra/2.1.2/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at callback (/rbd/pnpm-volume/a72f2b1e-1afc-4688-8e42-8faec7682622/node_modules/.registry.npmjs.org/fs-extra/2.1.2/node_modules/fs-extra/node_modules/graceful-fs/polyfills.js:295:20)
    at FSReqWrap.oncomplete (fs.js:154:5)
```

I tried running this and ran into this issue when trying to hit any expected endpoint to the api. uploading my images went fine before this.

Could you provide any info on what the json its expecting is? I could probably fix it if I knew what the service was looking for. Thanks for the help and for making this, very useful!

**Comment by NimaBoscarino** [comment]
Hey! It's been a while since I'd looked at this project. The issue there seems that I hadn't written something to ensure that a folder called "defs" existed, which would be used to store a file with the definition of the particular placeholder collection. I'd put the "defs" folder in the gitignore, so it never got pushed, and I hadn't written any code to create that folder. I've just pushed some new commits that should fix it, if you'd like to try it out now!

**Comment by NimaBoscarino** [comment]
I've also made a slight change to the format of the links. You _used_ to have to go to "http://localhost:3000/collections/Dogs/250/300" to create a placeholder image, but now you should go to "http://localhost:3000/Dogs/250/300" instead, without the word "collections".

**Comment by NimaBoscarino** [comment]
This project could totally use a bunch of refactoring and new features, so feel free to fork this and make any changes you'd like, and I'm happy to merge any pull requests you make!

**Comment by cupOJoseph** [comment]
Thanks Nima, I appreciate the reply a lot, this is super helpful.

**Comment by NimaBoscarino** [comment]
Any time!

**Comment by cupOJoseph** [comment]
Got it going! awesome! 

https://placeship.glitch.me/ship/400/300
